title: Berean's Blog
description: Theology of the Kingdom of God
baseurl: ""
url: "https://www.bereansblog.com"
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
header_pages:
  - index.md
  - blog.md
  - about.md
  - tags.md
  - categories.md
  - propositions.md
  - the_theocratic_kingdom.md
markdown: kramdown
permalink: /:year/:month/:day/:title/
exclude: [Gemfile, Gemfile.lock, vendor]